spring.datasource.url=jdbc:postgresql://localhost:5432/trading_system
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD_HERE

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
twelvedata.api.key=YOUR_API_KEY_HERE