package com.qullamaggie.tradingsystem.data.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents a notification generated by the system, e.g. when
 * a breakout signal triggers or a stop-loss is hit. Used to support
 * (not automate) the user's decision-making.
 *
 * @author Leia Haglund Sahlin, leia.haglund05@gmail.com
 * @version v1.0, 2026-06-13
 */
@Entity
@Getter @Setter
@Table(name = "alerts")
public class Alert {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "stock_id")
    private Stock stock;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    @Column(nullable = false, length = 30)
    private String type;

    @Column(precision = 12, scale = 4)
    private BigDecimal price;

    private boolean seen = false;

    @Column(columnDefinition = "TEXT")
    private String message;
}
